### Hi there 👋
🔭 I’m an undergraduate studying Accounting and a data enthusiast
🌱 I’m currently learning more on Machine Learning and Open Source Contributions.
👯 I’m also open to collaborations on Data Science/Machine Learning Projects 
📫 How to reach me: [LinkedIn](https://www.linkedin.com/in/miriam-odeyiany-919787245)
 Check out my [Portfolio](www.datascienceportfol.io/miriamodeyiany)
😄 Pronouns: She/Her
 [![An image of @odeyiany2's Holopin badges, which is a link to view their full Holopin profile](https://holopin.me/odeyiany2)](https://holopin.io/@odeyiany2)
<!--
**Odeyiany2/Odeyiany2** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
 😄 Pronouns: She/Her
- ⚡ Fun fact: ...
-->
